customhost = "employee.cmxnkilgtv5f.us-east-2.rds.amazonaws.com"
customuser = "kishore"
custompass = "kishoresonti"
customdb = "employee"
custombucket = "ademployee"
customregion = "us-east-2b"
customtable = "employee_image_table"
