customhost = "student.cw7urhisbpx0.us-east-1.rds.amazonaws.com"
customuser = "divakar"
custompass = "kasi1234"
customdb = "student"
custombucket = "adstudent"
customregion = "us-east-1a"
customtable = "student_pdf_table"
